add withdrawal adjustment
valitydev/newway pull request #100
Opened 2023-08-04 10:19 UTC by ggmaleva

2023-08-04 10:42 UTC, ggmaleva commented on src/main/resources/db/migration/V13__add_withdrawal_adjustment.sql
> +    new_domain_revision   bigint,
вот сюда обратить внимание. в зависимости от корректировки сохраняю либо новую ревизию домена, либо статус. мб что-то еще нужно?

2023-08-08 07:59 UTC, strug commented on src/main/java/dev/vality/newway/handler/event/stock/impl/withdrawal/WithdrawalAdjustmentStatusChangedHandler.java
> +    @Transactional(propagation = Propagation.REQUIRED)
вопрос со звездойчкой) для чего нам в рамках таких методов транзакции? Какую проблему мы ими закрываем?

2023-08-08 07:59 UTC, strug commented on src/main/resources/db/migration/V13__add_withdrawal_adjustment.sql
> +    new_domain_revision   bigint,
а зачем это делает новым полем? почему нельзя писать в те же поля проставляя каррент , просто ревизия очевидно может несколько раз меняться как и статус

2023-08-08 08:53 UTC, ggmaleva commented on src/main/java/dev/vality/newway/handler/event/stock/impl/withdrawal/WithdrawalAdjustmentStatusChangedHandler.java
> +    @Transactional(propagation = Propagation.REQUIRED)
> вопрос со звездойчкой) для чего нам в рамках таких методов транзакции? Какую проблему мы ими закрываем?

Хороший вопрос, коллега. Мы решаем проблему сознательности копипасты. Содержимое я поправил, а про аннотации забыл. Тут по сути оно не нужно. Нет сложной работы с БД.

2023-08-08 08:56 UTC, ggmaleva commented on src/main/resources/db/migration/V13__add_withdrawal_adjustment.sql
> +    new_domain_revision   bigint,
> а зачем это делает новым полем? почему нельзя писать в те же поля проставляя каррент , просто ревизия очевидно может несколько раз меняться как и статус

Тут не очень понял вопрос. Это поле и есть смысл записи в БД. Это один из вариантов корректировки выплаты. Либо изменение статуса, либо домена. Собственно в эти поля (new_withdrawal_status и new_domain_revision) я и пишу результат.

2023-08-08 10:23 UTC, ggmaleva commented on src/main/resources/db/migration/V13__add_withdrawal_adjustment.sql
> +    new_domain_revision   bigint,
Для платежей не меняется сама сущность платежа. Там табличка используется только чтоб данными заполнить сущность. 

https://github.com/valitydev/newway/blob/epic/db_schema_optimization/src/main/java/dev/vality/newway/handler/event/stock/impl/invoicing/adjustment/InvoicePaymentAdjustmentCreatedHandler.java#L75

2023-08-08 10:49 UTC, tolkonepiu requested changes

2023-08-08 10:49 UTC, tolkonepiu commented on src/main/resources/db/migration/V13__add_withdrawal_adjustment.sql
> +    CONSTRAINT withdrawal_adjustment_uniq UNIQUE (adjustment_id, sequence_id)
@ggmaleva а там нет никакого эвента с old cash flow и new cash flow?

2023-08-08 10:58 UTC, ggmaleva commented on src/main/resources/db/migration/V13__add_withdrawal_adjustment.sql
> +    CONSTRAINT withdrawal_adjustment_uniq UNIQUE (adjustment_id, sequence_id)
> @ggmaleva а там нет никакого эвента с old cash flow и new cash flow?

Да, есть. Причем, в обоих случая - и при смене статуса и при смене ревизии. По ним тоже инфу надо сохранить?

2023-08-08 11:00 UTC, tolkonepiu commented on src/main/resources/db/migration/V13__add_withdrawal_adjustment.sql
> +    CONSTRAINT withdrawal_adjustment_uniq UNIQUE (adjustment_id, sequence_id)
Да, там как раз нужные суммы изменений для финансистов. Тут можно глянуть, как это сделано для платежей, правда не уверен, что можно использовать как есть.

2023-08-08 11:04 UTC, ggmaleva commented on src/main/resources/db/migration/V13__add_withdrawal_adjustment.sql
> +    CONSTRAINT withdrawal_adjustment_uniq UNIQUE (adjustment_id, sequence_id)
> Да, там как раз нужные суммы изменений для финансистов. Тут можно глянуть, как это сделано для платежей, правда не уверен, что можно использовать как есть.

ок, покопаюсь и добавлю

2023-08-11 14:29 UTC, ggmaleva commented on src/main/resources/db/migration/V13__add_withdrawal_adjustment.sql
> +    CONSTRAINT withdrawal_adjustment_uniq UNIQUE (adjustment_id, sequence_id)
В итоге сделал подобно deposit с сохранением всех проводок. 
https://github.com/valitydev/newway/tree/epic/db_schema_optimization/src/main/java/dev/vality/newway/handler/event/stock/impl/deposit/adjustment

2023-08-15 15:03 UTC, tolkonepiu requested changes

2023-08-15 15:03 UTC, tolkonepiu commented on src/main/java/dev/vality/newway/handler/event/stock/impl/withdrawal/WithdrawalAdjustmentCreatedHandler.java
> +            Status newStatus = changesPlan.getNewStatus().getNewStatus();
А тут amount не заполняется?

2023-08-16 14:51 UTC, ggmaleva commented on src/main/java/dev/vality/newway/handler/event/stock/impl/withdrawal/WithdrawalAdjustmentCreatedHandler.java
> +            Status newStatus = changesPlan.getNewStatus().getNewStatus();
> А тут amount не заполняется?

Так при этом ChangesPlan только новый статус приходит. 
Ниже я проверяю заполнен ли CashFlow. И если заполнен, пишу amount.

2023-08-17 15:06 UTC, tolkonepiu commented on src/main/java/dev/vality/newway/handler/event/stock/impl/withdrawal/WithdrawalAdjustmentCreatedHandler.java
> +            Status newStatus = changesPlan.getNewStatus().getNewStatus();
> Так при этом ChangesPlan только новый статус приходит.

странно, ок, понял, тогда получается поле просто будет пустое, но с этим можно работать

2023-08-17 15:07 UTC, tolkonepiu approved these changes

2023-08-18 07:41 UTC, merged